### PR TITLE
fix: animate ambient animations based on the game time

### LINKED ISSUE #119: bug: windmill wind turbine speed is too fast and not constant
Same applies to virtual in-game time which is not constant, too.
What about the water that is also bound to the elapsed time?

### PR DESCRIPTION
**Pull request by fehnomenal**
fix #119

I created a function to allow listening for game time ticks. The callbacks get some info, including a delta for ambient animations.
This delta is calculated based on the game time seconds passed this tick. I just played around with the values which looked nice for the ocean.

### CODE REVIEW

File: src/composables/useGameTime.ts [hunk 1]
```diff
@@ -20,15 +21,46 @@ export default defineStore('gameTime', () => {
 
   const currentFactor = ref(GAME_TIME_FACTOR_REGULAR)
 
+  const listeners = new Set<OnTickFn>()
+
   function tick(deltaSeconds: number) {
     const gameTimeSecondsPassed = deltaSeconds * currentFactor.value
 
-    currentMilliseconds.value += gameTimeSecondsPassed * 1000
+    if (gameTimeSecondsPassed) {
```
Comment (toddeTV) [inline src/composables/useGameTime.ts:29]: question: Why is this check needed?

File: src/utils/duration.ts [hunk 2]
```diff
@@ -7,8 +7,10 @@ export class Duration {
     return new this(new Big(end.getTime() - start.getTime()))
   }
 
-  static fromSeconds(seconds: Big): Duration {
-    return new this(seconds.times(1000))
+  static fromSeconds(seconds: number): Duration
+  static fromSeconds(seconds: Big): Duration
```
Comment (toddeTV) [inline src/utils/duration.ts:11]: question: Why add overloads here when the return is the same? Only for IDE auto-completion and hints or do I miss something?

**Review by toddeTV — CHANGES_REQUESTED** [review]
Awesome work 🔥

Only two small questions :)

File: src/utils/duration.ts (hunk 2 above)
Comment (fehnomenal) [reply src/utils/duration.ts:11]: Hm, you're right. Probably left over from a previous iteration 😅

File: src/composables/useGameTime.ts (hunk 1 above)
Comment (fehnomenal) [reply src/composables/useGameTime.ts:29]: Iirc it is an optimization to skip callbacks when the game is paused and no progress would be reported. Pausing works by setting the current factor to zero.

The logic can be made more obvious by checking the factor instead.

**Comment by fehnomenal** [comment]
I addressed both of your points. Please take another look if you are satisfied :smiley:

File: src/composables/useGameTime.ts (hunk 1 above)
Comment (toddeTV) [reply src/composables/useGameTime.ts]: That makes perfect sense - I missed that. Thanks for the clarification! 😊

I've just resolved the merge conflicts and removed the redundant duplicate condition check.
